# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.BooleanField(verbose_name='性别')),
                ('age', models.PositiveIntegerField(verbose_name='年龄')),
                ('info', models.CharField(max_length=200, verbose_name='简介')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
