# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('girl_num', models.PositiveIntegerField(verbose_name='女生人数')),
                ('boy_num', models.PositiveIntegerField(verbose_name='男生人数')),
                ('description', models.CharField(max_length=256)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
