# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name_plural': '班级'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.CharField(max_length=256, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=32, verbose_name='班级'),
        ),
    ]
